### ISSUE TITLE
is anyone can help me

### ISSUE THREAD

**Issue by adbumanaf** [ogabrielinacio/esp_provisioning_ble#4]
this is not an issue .i want pass another custom data after connected with wifi.i want to pass the custom data to a particular endpoint .is it possible to do with this package .by using sendReceiveCustomData its only accept one argument

**Comment by adbumanaf** [comment]
when iam sending using send custom data it only shows one parameter .it only accepting one parameter .can anyone helpme or give any idea to do it

**Comment by ogabrielinacio** [comment]
Yes it is possible, you can create another event to handle this, and just use :
`var customAnswerBytes = await prov.sendReceiveCustomData(`
 `         Uint8List.fromList(`
 `           utf8.encode(event.customSendMessage),`
 `        ),`
 ` );`
 `var customAnswer = utf8.decode(customAnswerBytes);`
 `log.i("Custom data answer: $customAnswer");`

 And in response to your question about sending an array of data rather than just a single string, you can transmit a List<String> and then concatenate the elements into a single string using the following code snippet:

`list.reduce((value, element) => value + ',' + element)`
Here, i use a comma (",") to separate the elements, or you can use a semicolon (";") if you prefer, and then handle the data on your ESP32 device.

![firstImage](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/62192403/3c077c23-d26f-42d6-afe1-991e7ed72f26)
![SecondImage](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/62192403/8107dc4e-b93a-462d-b195-10da875d82c3)
![ThirdImage](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/62192403/aad78b5b-4a71-4084-8f2c-7da55bd95d4b)


I hope this is helpful!
